// Package objects provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package objects

import (
	"time"
)

// NewObject defines model for NewObject.
type NewObject struct {
	// Object's creation date
	CreatedAt time.Time `json:"created_at"`

	// Object's type
	Type string `json:"type"`
}

// Object defines model for Object.
type Object struct {
	// Object's creation date
	CreatedAt time.Time `json:"created_at"`

	// Object's unique ID
	Id int64 `json:"id"`

	// Object's type
	Type string `json:"type"`
}
