// Package objects provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package objects

import (
	"time"
)

// Object defines model for Object.
type Object struct {
	// CreatedAt Object's creation date
	CreatedAt time.Time `json:"created_at"`

	// FkType Object's type ID
	FkType int64 `json:"fk_type"`

	// Id Object's unique ID
	Id int64 `json:"id"`
}

// ObjectType defines model for ObjectType.
type ObjectType struct {
	// Id Objects' type ID
	Id int64 `json:"id"`

	// IsActive Objects' type activation status
	IsActive bool `json:"is_active"`

	// Value Objects' type definition value
	Value string `json:"value"`
}
