// Package objects provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package objects

import (
	"time"
)

// Object defines model for Object.
type Object struct {
	// CreatedAt Object's creation date
	CreatedAt time.Time `json:"created_at"`

	// Id Object's unique ID
	Id int64 `json:"id"`

	// Type Object's type ID
	Type int `json:"type"`
}
